FROM apache/spark:4.1.1

USER 0

# Install Python and curl
RUN apt-get update && \
    apt-get install -y python3 curl && \
    rm -rf /var/lib/apt/lists/*

# Install uv system-wide
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

USER 185